server:
  port: 8080
spring:
  application:
    name: iframe
  redis:
    host: 127.0.0.1
    port: 6379
# 主数据库
master:
  datasource:
    use-jndi: false
    jndi-name: jdbc/datasource
    url: jdbc:mysql://127.0.0.1:3306/iframe?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
    initial-size: 0
    min-idle: 10
    max-active: 100
    max-wait: 20000
# 从数据库
slave:
  datasource:
    use-jndi: false
    jndi-name: jdbc/datasource
    url: jdbc:mysql://127.0.0.1:3306/iframe1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
    initial-size: 0
    min-idle: 10
    max-active: 100
    max-wait: 20000
setting:
  elastic-job:
    zookeeper:
      serverList: 127.0.0.1:2181 #连接Zookeeper服务器的列表  如: host1:2181,host2:2181
      namespace: iframe